// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUBCqjBbo9_OkarWRIAYNDaVcWR3N4x28',
    appId: '1:976778725377:web:8fcb89c1738bac2b0a5800',
    messagingSenderId: '976778725377',
    projectId: 'socratize-daa4c',
    authDomain: 'socratize-daa4c.firebaseapp.com',
    storageBucket: 'socratize-daa4c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEP5Px06D75mAPlguWmPcQLdfTLcWAmY4',
    appId: '1:976778725377:android:59b4895589e0bacc0a5800',
    messagingSenderId: '976778725377',
    projectId: 'socratize-daa4c',
    storageBucket: 'socratize-daa4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-JsjROqO32Jxjh5A5_I0WbXlr_hWuWNE',
    appId: '1:976778725377:ios:789e3088214e03210a5800',
    messagingSenderId: '976778725377',
    projectId: 'socratize-daa4c',
    storageBucket: 'socratize-daa4c.firebasestorage.app',
    iosBundleId: 'com.example.socratize',
  );
}
